version: '3'
services:
    app:
        image: node:20-alpine
        build: .
        ports:
            - "3000:3000"
        command: npm start
    bd:
        image: "postgres"
        ports:
            - 5555:5432
        environment:
            - POSTGRES_PASSWORD=uv-RRbf2
            - POSTGRES_USER=vinicius
            - POSTGRES_DB=relatorio
        volumes:
            - pg-data:/var/lib/postgresql/data

volumes:
    pg-data:
    api:
